/* eslint-disable prettier/prettier */
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type ArticleDocument = Article & Document;

export enum ArticleType {
  Video = 'Video',
  News = 'News',
  LinkedIn = 'LinkedIn',
}

@Schema()
export class Article {
  @Prop({ required: true })
  baseUrl: string;

  @Prop({ required: true, unique: true })
  url: string;

  @Prop({ required: false })
  title: string;

  @Prop({ required: false })
  dateText: string;

  @Prop({ required: false })
  date: Date;

  @Prop({ required: false })
  teaser: string;

  @Prop({ required: true })
  image: string;

  @Prop({ type: String, enum: ArticleType, default: ArticleType.News })
  type: ArticleType;

  @Prop({ required: false })
  originalContent: string;

  @Prop({ required: false })
  generatedContent: string;

  createdAt: Date; // Auto-generated by Mongoose
  updatedAt: Date; // Auto-generated by Mongoose
}

export const ArticleSchema = SchemaFactory.createForClass(Article);
